base.url=https://www.nicequest.com/es
appium.url=http://127.0.0.1:4723


# Android
#android.udid=emulator-5554
android.udid=988d91315a594e545130
android.appPackage=com.netquest.pokey
android.appActivity=com.netquest.pokey.debug.MainActivity


# iOS
ios.deviceName=iPhone 15 Plus
ios.platformVersion=17.5
ios.app=url del Runner.app (creado dsd un mac)
# Alternativa si la app ya está instalada
ios.bundleId=com.netquest.pokey